name: Deploy Pages

on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Get Theme
        run: git submodule update --init --recursive
      - name: Update theme to Latest commit
        run: git submodule update --remote --merge
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: install hexo..
        run: |
          npm install
      - name: hexo generate...
        run: |
          hexo clean
          hexo g
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: ./public
            token: ${{ secrets.PAGES_TOKEN10 }}
